language: node_js
node_js:
  - 10

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g preact-cli
  - npm install
  - cd ./functions && npm install && cd ../
script:
  - yarn all_tests
  - cd ./functions && npm run test && cd ./
  - ng build --prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive


