language: node_js
node_js:
  - 10

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g preact-cli
  - npm install

script:
  - yarn all_tests
  - preact build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
deploy:
  provider: heroku
  api_key:
    secure: b842a229-75b7-460c-a073-a258d8fc41b5
  app: gridcloud
  on:
    repo: KindulovMikhail/grid-cloud

