language: node_js
node_js:
  - 10
sudo: true

addons:
  chrome: stable

branches:
  only:
    - travis

deploy:
  provider: heroku
  app: gridcloud
  api_key:
    secure: "0fac01a3-0fe8-4e7b-b184-433ff72bd82a"

