language: node_js
node_js:
  - 10
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - yarn all_tests

deploy:
  provider: heroku
  app: gridcloud
  api_key:
    secure: b842a229-75b7-460c-a073-a258d8fc41b5
  on:
      branch: master

